### ISSUE TITLE
Questão 1

### ISSUE THREAD

**Issue by fakebmarchete** [bmarchete/projeto-empresas#1]
Você gostaria de gmail com maiuscula ou minuscula❓

**Comment by bmarchete** [comment]
Tanto faz, você decide! @fakebmarchete

**Comment by fakebmarchete** [comment]
O código então é

```sql
select * from empresas;
```

**Comment by bmarchete** [comment]
Puxa, vc salvou meu dia. Testei aqui era isso mesmo! 👍
